### PR TITLE
LPS-167302 | Add Autom. test FDSCustomView#CanBeDeleted

### PR DESCRIPTION
**Pull request by mateussandes23**
**Test Plan:**

- Given A dataset display instance of a component
- And Given A custom view is created
- When Deleting the custom view
- Then Assert the custom view no longer exists

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-167302

### CODE REVIEW

**Comment by mateussandes23** [comment]
ci:test:frontend:nocompile

**Comment by mateussandes23** [comment]
ci:test:sf

**Comment by mateussandes23** [comment]
ci:test:frontend:nocompile

**Comment by mateusralv** [comment]
Forwarded manually: https://github.com/liferay-frontend/liferay-portal/pull/2857

**Pull request closed without merging**
