### PR TITLE
LPS-164602 | Add Autom. test FDSCustomView#ManagementBarCanBeLocalized

### PR DESCRIPTION
**Pull request by eltonccdantas**
**Test Plan**

- Given: localized FDS sample portlet
- And Given: site URL localized to Spanish //localhost:8080/es/*
- When: on customized tab view
- Then: Filter button is localized //assert Filtro is present in first navbar-nav element
- And Then: Search help text is localized //assert Buscar is present in search field
- And Then: Change Display dropdown items are localized
- And Then: Custom Views dropdown items are localized
- And Then: Ellipsis dropdown "Save" is localized
- And Then: Reset Filters link is localized

**JIRA Ticket:
https://issues.liferay.com/browse/LPS-164602**

### CODE REVIEW

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
https://issues.liferay.com/browse/LPS-164602

**Comment by eltonccdantas** [comment]
ci:test:frontend:nocompile

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by eltonccdantas** [comment]
ci:test:sf

**Comment by john-co** [comment]
same suggestion as: https://github.com/mateusralv/liferay-portal/pull/18#discussion_r999913425

**Comment by john-co** [comment]
We should also start looking into sending PRs to liferay-frontend which has it's master branch up to date more frequently.

**Comment by john-co** [comment]
@mateusralv you may want to look into setting up an auto update feature such as OriginAI: https://liferay.atlassian.net/wiki/spaces/SUPPORT/pages/1956152644/OriginAI

**Comment by john-co** [comment]
liferay-frontend github uses a more [complicated script](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1409615973/liferay-frontend+repo+sync) but syncs itself every 1 minute instead of every hour with OriginAI. I just use OriginAI since it was easy to setup.

**Comment by eltonccdantas** [comment]
ci:test:frontend:nocompile

**Comment by john-co** [comment]
hint to fix url: https://issues.liferay.com/browse/LRQA-77007

**Comment by eltonccdantas** [comment]
> possible clue to fix url: https://issues.liferay.com/browse/LRQA-77007

I've changed to :
var portalURL = PropsUtil.get("portal.url");
			Navigator.openSpecificURL(url = "${portalURL}/es/frontend-data-set-test-page/");

**Comment by john-co** [comment]
Thanks! Please send to `liferay-frontend` user for further review. @mateusralv 's master branch is 200+ commits behind.

**Comment by john-co** [comment]
Let's send PRs to `liferay-frontend` from now on.

**Comment by eltonccdantas** [comment]
> 

Ok, I've just sent a new PR to **liferay-frontend**

**Pull request closed without merging**
