### PR TITLE
LRQA-76493 | Stabilize CPCommerceShipments#CreateMultipleShipmentsForOneOrder 

### PR DESCRIPTION
**Pull request by mateusralv**
**Background:**
The test is failing [13% of executions](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6623/), to ensure full loading of the Frame was used the following macros: 
1. WaitForLiferayEvent();
2. WaitForPageLoad();
3. selectFrameNoLoading();
---
I created two files. 
The first only with the same test but using each macro:

1. CreateMultipleShipmentsForOneOrder**WaitForLiferayEvent**
2. CreateMultipleShipmentsForOneOrder**WaitForPageLoad**
3. CreateMultipleShipmentsForOneOrder**selectFrameNoLoading**

The second with the three different macros:

1. createShipment**WaitForLiferayEvent**
2. createShipment**WaitForPageLoad**
3. createShipment**selectFrameNoLoading**
---
In Jenkins:
1. [#6​64​2](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6642/)
2. [#6​64​3](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6643/)
3. [#6​64​4](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6644/)

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:commerce

**Comment by mateusralv** [comment]
UPDATE: Replace Refresh() with a WaitElementNotPresent() with the loading portlet path.

Run in RCA: [#6​67​3](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6673/)

**Comment by mateusralv** [comment]
ci:test:commerce

**Comment by mateusralv** [comment]
Create a macro that refreshes without waiting for the SPA

RCA run: 
[#6​69​5](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6695/) for CPCommerceShipments#CreateMultipleShipmentsForOneOrder
[#6​69​6](https://test-1-1.liferay.com/job/root-cause-analysis-tool/6696/) for CPCommerceShipments#CreateMultipleShipmentsForOneOrder

**Comment by john-co** [comment]
ci:test:commerce

**Pull request closed without merging**
